# Generated by Django 4.1.1 on 2022-10-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='method',
            field=models.CharField(default='cod', max_length=100),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
