# Generated by Django 4.1.1 on 2022-10-03 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_order_amount_order_method_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
