# Generated by Django 4.1.1 on 2022-10-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
