# Generated by Django 4.1.1 on 2022-10-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
