# Generated by Django 4.1.1 on 2022-10-05 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_oldcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldcart',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.order'),
        ),
    ]
