# Generated by Django 4.1.1 on 2022-10-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_oldcart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.CharField(default='Cash On Delivery', max_length=100),
        ),
    ]
