# Generated by Django 4.1.1 on 2022-10-06 06:56

import cropperjs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cropperjs.models.CropperImageField(blank=True, null=True, upload_to='assets/images'),
        ),
    ]
