# Generated by Django 4.1.1 on 2022-10-18 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.category'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.product'),
        ),
    ]
