# Generated by Django 4.1.1 on 2022-10-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
