# Generated by Django 4.1.1 on 2022-10-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0014_offers_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
