# Generated by Django 4.1.1 on 2022-10-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_offers_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='code',
        ),
    ]
