# Generated by Django 4.1.1 on 2022-10-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_coupon_min_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='max_value',
            field=models.IntegerField(default=0),
        ),
    ]
