# Generated by Django 4.1.1 on 2022-09-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
